language: python

dist: xenial

python:
  - "3.7"
  - "nightly"
install:
  - pip install -U .[test]
  - pip install codecov
script:
  - python -m pytest tests --cov-report term-missing --cov ddtrace_graphql

after_script:
  - codecov
